services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - Backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: http://localhost:5000
    ports:
      - "3000:80"